import { mkdir, writeFile } from 'node:fs/promises';
import { z } from 'zod';
import {
  AgentIdentitySchema,
  AgentResolutionSchema,
  AgentPresenceSchema,
  AgentModeSchema,
  AgentTransportSchema,
  BehaviouralProfileDeltaSchema,
  ContextualReliabilitySummarySchema,
  CompletionOutcomeSchema,
  CounterpartyBriefSchema,
  ContractRevisionSchema,
  DelegationCredentialSchema,
  ExpectationManifestSchema,
  FactCheckResultSchema,
  FeedbackSchema,
  FeedbackDimensionSchema,
  FeedbackRequestSchema,
  InteractionContractSchema,
  InteractionCompletionReportSchema,
  InteractionConclusionSchema,
  InteractionEventSchema,
  InteractionFeedbackSchema,
  FederatedInteractionSchema,
  LiveSessionAcceptanceSchema,
  LiveSessionActivationSchema,
  LiveSessionEventSchema,
  LiveSessionOfferSchema,
  LiveSessionStateRecordSchema,
  HostedMessageSchema,
  HostedThreadSchema,
  PublicAgentCardSchema,
  RequirementAssessmentSchema,
  ReceiptSchema,
  RecordAttestationSchema,
  RiskDecisionSchema,
  SourceRecordEnvelopeSchema,
  SuccessCriterionAssessmentSchema,
  TrustEnvelopeSchema,
  LearningEligibilityDecisionSchema,
} from '@openclasp/protocol';

const schemas = {
  agent_identity: AgentIdentitySchema,
  agent_resolution: AgentResolutionSchema,
  delegation_credential: DelegationCredentialSchema,
  expectation_manifest: ExpectationManifestSchema,
  interaction_contract: InteractionContractSchema,
  contract_revision: ContractRevisionSchema,
  trust_envelope: TrustEnvelopeSchema,
  interaction_event: InteractionEventSchema,
  fact_check_result: FactCheckResultSchema,
  receipt: ReceiptSchema,
  record_attestation: RecordAttestationSchema,
  feedback: FeedbackSchema,
  risk_decision: RiskDecisionSchema,
  agent_transport: AgentTransportSchema,
  agent_presence: AgentPresenceSchema,
  agent_mode: AgentModeSchema,
  public_agent_card: PublicAgentCardSchema,
  federated_interaction: FederatedInteractionSchema,
  live_session_offer: LiveSessionOfferSchema,
  live_session_acceptance: LiveSessionAcceptanceSchema,
  live_session_activation: LiveSessionActivationSchema,
  live_session_event: LiveSessionEventSchema,
  live_session_state_record: LiveSessionStateRecordSchema,
  hosted_message: HostedMessageSchema,
  hosted_thread: HostedThreadSchema,
  requirement_assessment: RequirementAssessmentSchema,
  counterparty_brief: CounterpartyBriefSchema,
  completion_outcome: CompletionOutcomeSchema,
  success_criterion_assessment: SuccessCriterionAssessmentSchema,
  interaction_completion_report: InteractionCompletionReportSchema,
  feedback_dimension: FeedbackDimensionSchema,
  feedback_request: FeedbackRequestSchema,
  interaction_feedback: InteractionFeedbackSchema,
  interaction_conclusion: InteractionConclusionSchema,
  learning_eligibility_decision: LearningEligibilityDecisionSchema,
  behavioural_profile_delta: BehaviouralProfileDeltaSchema,
  contextual_reliability_summary: ContextualReliabilitySummarySchema,
  source_record_envelope: SourceRecordEnvelopeSchema,
};
await mkdir('schemas/v0.1', { recursive: true });
await Promise.all(
  Object.entries(schemas).map(([name, schema]) =>
    writeFile(
      `schemas/v0.1/${name}.schema.json`,
      `${JSON.stringify(z.toJSONSchema(schema, { target: 'draft-2020-12' }), null, 2)}\n`,
    ),
  ),
);
